/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ping;


/**
 *
 * @author david
 */
public class Formulario extends javax.swing.JFrame {

    /**
     * Creates new form Formulario
     */
    public Formulario() {
        initComponents();
        cmd = new Command(txtResult);
        thread = new Thread(cmd);
        thread.setDaemon(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        txtResult = new javax.swing.JTextArea();
        btnPing = new javax.swing.JButton();
        bntPingN = new javax.swing.JButton();
        txtIpAdress = new javax.swing.JTextField();
        btnPingT = new javax.swing.JButton();
        btnPingL = new javax.swing.JButton();
        btnTracert = new javax.swing.JButton();
        btnTracertD = new javax.swing.JButton();
        btnTracertH = new javax.swing.JButton();
        btnNslookup = new javax.swing.JButton();
        btnNetsh = new javax.swing.JButton();
        btnStop = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtBeforeResult = new javax.swing.JTextArea();
        btnSave = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtResult.setColumns(20);
        txtResult.setRows(5);
        jScrollPane1.setViewportView(txtResult);

        btnPing.setText("Ping");
        btnPing.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPingActionPerformed(evt);
            }
        });

        bntPingN.setText("Ping -n");
        bntPingN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntPingNActionPerformed(evt);
            }
        });

        txtIpAdress.setText("google.com.ec");

        btnPingT.setText("Ping -t");
        btnPingT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPingTActionPerformed(evt);
            }
        });

        btnPingL.setText("Ping -l");
        btnPingL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPingLActionPerformed(evt);
            }
        });

        btnTracert.setText("Tracert");
        btnTracert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTracertActionPerformed(evt);
            }
        });

        btnTracertD.setText("Tracert -d");
        btnTracertD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTracertDActionPerformed(evt);
            }
        });

        btnTracertH.setText("Tracert -h");
        btnTracertH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTracertHActionPerformed(evt);
            }
        });

        btnNslookup.setText("Nslookup");
        btnNslookup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNslookupActionPerformed(evt);
            }
        });

        btnNetsh.setText("netsh");
        btnNetsh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNetshActionPerformed(evt);
            }
        });

        btnStop.setText("stop");
        btnStop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStopActionPerformed(evt);
            }
        });

        txtBeforeResult.setColumns(20);
        txtBeforeResult.setRows(5);
        jScrollPane2.setViewportView(txtBeforeResult);

        btnSave.setText("save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnTracert)
                                .addGap(18, 18, 18)
                                .addComponent(btnTracertD)
                                .addGap(18, 18, 18)
                                .addComponent(btnTracertH))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnNslookup)
                                .addGap(18, 18, 18)
                                .addComponent(btnNetsh))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnPing)
                                .addGap(18, 18, 18)
                                .addComponent(bntPingN)
                                .addGap(18, 18, 18)
                                .addComponent(btnPingT))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtIpAdress, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(75, 75, 75)
                                .addComponent(btnStop)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnSave)
                            .addComponent(btnPingL))))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 534, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(13, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtIpAdress, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnStop)
                            .addComponent(btnSave))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnPing)
                            .addComponent(bntPingN)
                            .addComponent(btnPingT)
                            .addComponent(btnPingL))
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnTracert)
                            .addComponent(btnTracertD)
                            .addComponent(btnTracertH))
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnNslookup)
                            .addComponent(btnNetsh))
                        .addGap(34, 34, 34)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void commandStart(int option) {
        EnableBtns(false);
        cmd.setIpAddress(this.txtIpAdress.getText());
        cmd.setOption(option);
        cmd.setBand(true);
        thread = new Thread(cmd);
        thread.setDaemon(true);
        thread.start();

    }
    private void EnableBtns(boolean flag){
        btnNetsh.setEnabled(flag);
        btnNslookup.setEnabled(flag);
        btnPing.setEnabled(flag);
        btnPingL.setEnabled(flag);
        btnPingT.setEnabled(flag);
        bntPingN.setEnabled(flag);
        btnTracert.setEnabled(flag);
        btnTracertD.setEnabled(flag);
        btnTracertH.setEnabled(flag);
        
    }
    private void btnPingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPingActionPerformed
        // TODO add your handling code here:
        commandStart(0);
    }//GEN-LAST:event_btnPingActionPerformed

    private void bntPingNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntPingNActionPerformed
        commandStart(1);
    }//GEN-LAST:event_bntPingNActionPerformed

    private void btnPingTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPingTActionPerformed

        commandStart(2);
    }//GEN-LAST:event_btnPingTActionPerformed

    private void btnPingLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPingLActionPerformed

        commandStart(3);
    }//GEN-LAST:event_btnPingLActionPerformed

    private void btnStopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStopActionPerformed
       
        cmd.setBand(false);
        Thread joinThread = new Thread(() -> {
            try {
                thread.join(); // Esperar a que termine
                 EnableBtns(true);
            } catch (InterruptedException e) {
                // Manejar excepción si ocurre
                System.out.println(e.getMessage());
            }
        });
        joinThread.start();
        txtResult.setText(txtResult.getText() + "\n Run stoped");
//        txtBeforeResult.setText(txtResult.getText());
    }//GEN-LAST:event_btnStopActionPerformed

    private void btnTracertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTracertActionPerformed
        // TODO add your handling code here:
        commandStart(4);
    }//GEN-LAST:event_btnTracertActionPerformed

    private void btnTracertDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTracertDActionPerformed
        // TODO add your handling code here:
        commandStart(5);
    }//GEN-LAST:event_btnTracertDActionPerformed

    private void btnTracertHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTracertHActionPerformed
        // TODO add your handling code here:
        commandStart(6);
    }//GEN-LAST:event_btnTracertHActionPerformed

    private void btnNslookupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNslookupActionPerformed
        // TODO add your handling code here:
        commandStart(7);
    }//GEN-LAST:event_btnNslookupActionPerformed

    private void btnNetshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNetshActionPerformed
        // TODO add your handling code here:
        commandStart(8);
    }//GEN-LAST:event_btnNetshActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        txtBeforeResult.setText(txtResult.getText());
    }//GEN-LAST:event_btnSaveActionPerformed
    
    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Formulario().setVisible(true);
//            }
//        });
//    }
    //Mis atributos
    private Command cmd;
    private Thread thread;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntPingN;
    private javax.swing.JButton btnNetsh;
    private javax.swing.JButton btnNslookup;
    private javax.swing.JButton btnPing;
    private javax.swing.JButton btnPingL;
    private javax.swing.JButton btnPingT;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnStop;
    private javax.swing.JButton btnTracert;
    private javax.swing.JButton btnTracertD;
    private javax.swing.JButton btnTracertH;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea txtBeforeResult;
    private javax.swing.JTextField txtIpAdress;
    private javax.swing.JTextArea txtResult;
    // End of variables declaration//GEN-END:variables
}
